inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'config/routes.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/api/v1/participants_controller.rb'
